server:
  port: 8901

logging:
  level:
    root: INFO
    org.llled.ledbloom: DEBUG

ledbloom:
  ddp-listen-port: 4048
  frame-width: 64
  frame-height: 48
  ip-block: ""
  discovery-interval-seconds: 60
  device-timeout-minutes: 5
  mdns-discovery-enabled: true
  ip-range-discovery-enabled: true
  skip-ips: []
